### ISSUE TITLE
Unused parameter

### ISSUE THREAD

**Issue by zennard** [zeldon-0/SoftwareMethodology.Practice1#1]
https://github.com/zeldon-0/SoftwareMethodology.Practice1/blob/0a45bb4d97e50db6373d21865674b2e2925bef3b/SoftwareMethodology.Practice1/Domain/Map.cs#L54

Please remove 'allCountries' parameter if it's not used.

**Comment by zeldon-0** [comment]
Thank you for noticing this. This has now been fixed.
