### ISSUE TITLE
Missing validation

### ISSUE THREAD

**Issue by zennard** [zeldon-0/SoftwareMethodology.Practice1#2]
https://github.com/zeldon-0/SoftwareMethodology.Practice1/blob/0a45bb4d97e50db6373d21865674b2e2925bef3b/SoftwareMethodology.Practice1/Domain/Map.cs#L56

Please add missing validation for the case when passed countryName is longer than 25 characters.

**Comment by zeldon-0** [comment]
Thank you for noticing this. This has now been fixed.
