### ISSUE TITLE
Iterators

### ISSUE THREAD

**Issue by IanaKhitsko** [zeldon-0/SoftwareMethodology.Practice1#3]
https://github.com/zeldon-0/SoftwareMethodology.Practice1/blob/be297cad21d3a2115a66232cbe7c844ea5c4f5dd/SoftwareMethodology.Practice1/Domain/Map.cs#L83

Don't use acronyms, please use normal namings when iterating (c). Same all over the code.

**Comment by zeldon-0** [comment]
Updated all the LINQ predicates to use regular parameter names with the latest commit.
