### ISSUE TITLE
Exception text

### ISSUE THREAD

**Issue by IanaKhitsko** [zeldon-0/SoftwareMethodology.Practice1#4]
https://github.com/zeldon-0/SoftwareMethodology.Practice1/blob/be297cad21d3a2115a66232cbe7c844ea5c4f5dd/SoftwareMethodology.Practice1/Domain/Map.cs#L62

What if Width and Length will be changed? Then for sure someone will forget to change the text

**Comment by zeldon-0** [comment]
Good catch. The exception message string has been updated to interpolate the const's value, instead.
